import type { Metadata } from 'next'
import { cookies, headers } from 'next/headers'
import localFont from 'next/font/local'
import '@/app/globals.css'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const headersList = await headers()
  const serverCookies = await cookies()
  const systemTheme = headersList.get('sec-ch-prefers-color-scheme')
  const theme = serverCookies.get('theme')?.value ?? systemTheme

  return (
    <html lang="en">
      <body
        className={`${theme === 'dark' ? theme : ''} ${geistSans.variable} ${geistMono.variable} antialiased text-zinc-800 dark:text-gray-200 bg-white dark:bg-zinc-900 sm:max-w-screen-sm md:max-w-screen-md mx-auto`}
      >
        {children}
      </body>
    </html>
  )
}
